### ISSUE TITLE
Loading animation

### ISSUE THREAD

**Issue by toroidal-code** [spectra-music/spectra#11]
Maybe modify the third one of these?
[spinkit](http://tobiasahlin.com/spinkit/)
To look like the logo (without color)

**Comment by weswigham** [comment]
[See preview here.](https://dl.dropboxusercontent.com/u/99862/loader.html)
Opinions?
(Committed to repo with commit 3c13db2)

**Comment by weswigham** [comment]
@kristenmills @toroidal-code @zellio  and you know what? @smy2748

**Comment by kristenmills** [comment]
I like it

**Comment by toroidal-code** [comment]
:+1:

**Comment by weswigham** [comment]
This has been merged into dev
