### ISSUE TITLE
circular dependency detected while autoloading constant 'WelcomeController'

### ISSUE THREAD

**Issue by kristenmills** [spectra-music/spectra#22]
This happens everytime i start the server and first try to access the site. I refresh and it goes away and continues to work but we should figure out why this is happens.

**Comment by kristenmills** [comment]
Has anyone else noticed this problem? It appears to have just gone away for me. @toroidal-code

**Comment by toroidal-code** [comment]
I've never seen this error.

**Comment by kristenmills** [comment]
alright I'll close it.  Idk what it was
