### ISSUE TITLE
Rails 4.2

### ISSUE THREAD

**Issue by kristenmills** [spectra-music/spectra#38]
Do it. You won't.

**Comment by weswigham** [comment]
:+1:

**Comment by toroidal-code** [comment]
What are the major differences? What sort of things would be required in migrating?

**Comment by toroidal-code** [comment]
I did it.

I DID IT ONE BETTER.

**RAILS 5: THE VIDEOGAME HAS ARRIVED**

(coming to a store near you. while supplies last. provided courtesy of #40)

**Comment by weswigham** [comment]
!!!
