### ISSUE TITLE
Persistent preferences

### ISSUE THREAD

**Issue by toroidal-code** [spectra-music/spectra#5]
I don't really know how to do preferences in a Rails application.
But we're going to need some things, such as preferred file type, 
saving metadata edits to disk, etc.

Maybe @kristenmills has an idea?

**Comment by toroidal-code** [comment]
Maybe something like [rails-settings-cached](https://github.com/huacnlee/rails-settings-cached) would work?

**Comment by kristenmills** [comment]
Are the preferences often changing or not. Because if they don't change often, they should go on an initializer.

**Comment by nickserv** [comment]
If the preferences should be easily changeable at runtime by users, we should use something like [Active Admin](http://activeadmin.info). Otherwise, we should use an initializer as @kristenmills recommends.

**Comment by toroidal-code** [comment]
These would be runtime preferences.

**Comment by toroidal-code** [comment]
ActiveAdmin looks too pre-baked. I was leaning more towards something that we could build a JSON API around, similar to how the rest of the application functions. It looks like rails-settings-cached would let us do this.
